name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: mise action
        uses: jdx/mise-action@v2.0.0
      - name: Run Tests
        run: mise run tests